version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8080"
    links:
      - "db:some-redis"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 200m
        reservations:
          cpus: '0.20'
          memory: 100m
  db:
    image: "redis:alpine"
    hostname: some-redis
    ports:
      - "6379:6379"
